### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by nelsonic** [sandfox/aws-arn-parser#2]
Hi @sandfox, 
We are looking for a way to parse _any_/_all_ formats of ARN.
At present, this module only supports the older ARNs (_with 6 segments_) but would not understand a  Lambda ARN (_which can have 7 or 8 segments_): 
http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-lambda

Would you accept a PR updating it to support more ARN types?

**Comment by sandfox** [comment]
Hi @nelsonic, 

Totally down for improvements etc and more than happy to publish them! I've been meaning to de-coffee script this for ages, so if you can wait a few hours I should have the non-cs branch version on master to work from.

**Comment by nelsonic** [comment]
@sandfox I can de-coffee it if you like ...

**Comment by sandfox** [comment]
@nelsonic ahh, just saw this after I de-cs'd it! I've just pushed up a new version. The changes are minor.

**Comment by zyrorl** [comment]
updates on this?

**Comment by sandfox** [comment]
this is now fixed-ish in the v2 version available as `@sandfox/arn` on npm. It now long attempts to parse beyond the resource component so any extra colons in thing such as lambda names are ignored

e.g 
```js
"arn:aws:lambda:region:account-id:event-source-mappings:event-source-mapping-id"
```

```js
{ partition: 'aws',
  service: 'lambda',
  region: 'region',
  accountID: 'account-id',
  resource: 'event-source-mappings:event-source-mapping-id' }
```
