### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by robertbullen** [sandfox/aws-arn-parser#3]
TypeScript definitions would make this module easier to consume. Would you accept such a PR Alternatively, I could submit them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by sandfox** [comment]
I'd gladly accept a PR 😄

**Comment by sandfox** [comment]
btw, I've now published a v2 of this module under the name `@sandfox/arn` with a slightly different api

**Comment by robertbullen** [comment]
Good to know. I'll make the type definitions for the new API. I'll submit a PR by end of week.

**Comment by sandfox** [comment]
closed by #5
